version: "3.4"
services:
  timeseries-api:
    container_name: timeseries-api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - mongo
      - timeseries-service
    ports:
      - '2601:80'
    environment:
        ## Api Specific
      - 'db:users=kk'

      
  timeseries-service:
    container_name: timeseries-service
    build:
      context: .
      dockerfile: Service/Dockerfile
    depends_on:
      - mongo
    ports:
      - '2602:440'
    environment:
        ## Api Specific
      - 'db:authorizationserver=kk'

## External
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  
networks:
  default: